openapi: 3.0.3

info:
  title: Dummy API Specification
  version: 0.0.1

paths:
  /health:
    get:
      operationId: get_health_status
      description: Returns the current health status of the Service
      responses:
        200:
          description: The health check result
        204:
          description: When theres no health checks registered
        500:
          description: At least one health check could not complete or an error occurred
        503:
          description: At least one health check is not OK
